import "./ImprintContent.css"
import LinkButton from "../LinkButton/LinkButton";
import GenericPageHeadline from "../GenericPageHeadline/GenericPageHeadline";

const ImprintContent = () => {


    return (
        <div className="impressum-container">
            <LinkButton URL={"/"} text={"Back to Shop"}/>
            <div className="impressum-content">

                <GenericPageHeadline text={"Imprint"}/>
                <p>Information according to § 5 TMG</p>
                <p>Max Muster <br/> Musterweg<br/>12345 Musterstadt <br/></p>
                <p><
                    strong>Represented by: </strong><br/>Max Muster<br/>
                </p>
                <p><
                    strong>Contact:</strong> <br/> Tel.: 01234-789456<br/> Fax: 1234-56789<br/>E-Mail: <a
                    href="mailto:max@muster.de">max@muster.de</a><br/>
                </p>
                <p>
                    <strong>Register entry: </strong><br/>Entry in the register court:
                    Musterstadt<br/> Registration number: 12345<br/>
                </p>
                <p>
                    <strong>Sales tax ID: </strong> <br/>
                    Sales tax identification number according to §27a: 00000.<br/><br/>
                    <strong>Business ID: </strong><br/>
                    Musterwirtschaftsid<br/>
                </p>
                <p>
                    <strong>Supervisory Authority:</strong><br/>
                    Musteraufsicht Musterstadt<br/>
                </p>
                <br/>
                Imprint generated by <a href="https://www.impressum-generator.de">impressum-generator.de</a>
            </div>

        </div>

    )
}
export default ImprintContent;
